# Generated by Django 2.2.5 on 2019-09-30 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='区域')),
                ('subnet', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='IP地址段')),
                ('bandwidth', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='出口带宽')),
                ('contact', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='机房地址')),
                ('contract_date', models.CharField(max_length=30, verbose_name='合同时间')),
                ('describe', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('needed_cabinet', models.BooleanField(default=True, verbose_name='是否需要渲染机架图')),
            ],
            options={
                'verbose_name_plural': '所属区域',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='厂家供应商')),
                ('contact', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('describe', models.TextField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '厂家信息',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('ipadd', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='IP地址')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='序列号')),
                ('asset_type', models.CharField(choices=[('cloud_host', '云主机'), ('virtual_machine', '虚拟机'), ('virtual_node', '虚拟机节点'), ('container_node', '容器主机节点'), ('server', '物理机'), ('switch', '交换机'), ('route', '路由器'), ('firewall', '防火墙'), ('lb', '负载均衡设备')], default='virtual_machine', max_length=64, verbose_name='资产类型')),
                ('status', models.SmallIntegerField(choices=[(0, '激活'), (1, '停用'), (2, '故障')], default=0, verbose_name='设备状态')),
                ('cpu', models.CharField(blank=True, max_length=60, null=True)),
                ('disk', models.CharField(blank=True, max_length=60, null=True)),
                ('memory', models.CharField(blank=True, max_length=60, null=True)),
                ('cabinet', models.CharField(blank=True, max_length=32, null=True, verbose_name='机柜号')),
                ('uhight', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 4), (9, 0)], null=True, verbose_name='u高')),
                ('railnum', models.IntegerField(blank=True, null=True, verbose_name='导轨位置')),
                ('put_shelf_time', models.DateField(verbose_name='上线时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('comment', models.TextField(blank=True, default='', max_length=128, verbose_name='备注')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Area', verbose_name='区域')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufacturer', verbose_name='厂家')),
            ],
            options={
                'verbose_name_plural': '账户信息',
                'ordering': ['-ctime'],
            },
        ),
    ]
