# Generated by Django 2.2.5 on 2019-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('nickname', models.CharField(max_length=32, verbose_name='平台简称')),
                ('describe', models.CharField(blank=True, max_length=60, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '所属公司',
            },
        ),
    ]
