# Generated by Django 2.2.5 on 2019-10-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_belong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='belong',
        ),
    ]
