# Generated by Django 2.2.5 on 2019-10-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_belong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Belong',
        ),
    ]
