# Generated by Django 3.2 on 2021-07-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ci_cd_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.IntegerField(blank=True)),
                ('xiang_mu', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=255)),
                ('jar_pack', models.CharField(blank=True, max_length=255)),
                ('jar_url', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(blank=True)),
            ],
        ),
    ]
