# Generated by Django 3.2 on 2021-07-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0002_ci_cd_info_a_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ci_cd_info',
            name='a_ID',
        ),
        migrations.RemoveField(
            model_name='ci_cd_info',
            name='id',
        ),
        migrations.AddField(
            model_name='ci_cd_info',
            name='ID',
            field=models.IntegerField(auto_created=True, blank=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
