# Generated by Django 3.2 on 2021-07-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0003_auto_20210720_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci_cd_info',
            name='ID',
            field=models.IntegerField(auto_created=True, blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
