# Generated by Django 3.2 on 2021-07-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0004_alter_ci_cd_info_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ci_cd_info',
            new_name='info',
        ),
    ]
