# Generated by Django 3.2 on 2021-07-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0005_rename_ci_cd_info_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='ID',
            field=models.AutoField(auto_created=True, max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
