# Generated by Django 3.2 on 2021-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0006_alter_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='requestid',
            field=models.IntegerField(blank=True, db_index=True, unique=True),
        ),
    ]
