# Generated by Django 3.2 on 2021-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0007_alter_info_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='requestid',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
